services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stream-resolver-api
    expose:
      - "${PORT:-8080}"
    environment:
      # Configuración del servidor
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=${PORT:-8080}
      
      # Conexiones
      - REDIS_URL=redis://redis:6379

      # Seguridad (configurar en producción)
      - API_KEY=${API_KEY:-}
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
      - ALLOWLIST_HOSTS=${ALLOWLIST_HOSTS:-}
      
      # Configuración del navegador
      - PUPPETEER_HEADLESS=true
      - NAV_TIMEOUT_MS=30000
      - MAX_WAIT_MS=15000
      - USER_AGENT=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
      
      # Configuración del Proxy
      - PROXY_ENABLED=${PROXY_ENABLED:-false}
      - PROXY_ENDPOINT=${PROXY_ENDPOINT:-}
      - PROXY_USERNAME=${PROXY_USERNAME:-}
      - PROXY_PASSWORD=${PROXY_PASSWORD:-}

      # Pool de navegadores
      - MAX_CONCURRENT_PAGES=5
      - BROWSER_POOL_SIZE=2
      
      # Logging
      - LOG_LEVEL=info
      
      # Rate limiting (para la API)
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX:-100}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-60000}
      
      # Session
      - SESSION_SECRET=${SESSION_SECRET:-default-secret-change-in-production}
    
    # Límites de recursos
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    
    # Configuración de red
    networks:
      - resolver-network
    
    depends_on:
      - redis

    # Reinicio automático
    restart: unless-stopped
    
    # Configuración de seguridad
    security_opt:
      - no-new-privileges:true
    
    # Capabilities mínimas necesarias para Chromium
    cap_add:
      - SYS_ADMIN
    
    # Shared memory para Chromium
    shm_size: 2gb

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stream-resolver-worker
    command: node dist/worker.js
    environment:
      # Configuración del servidor
      - NODE_ENV=production
      
      # Conexiones
      - REDIS_URL=redis://redis:6379
      
      # Configuración del navegador
      - PUPPETEER_HEADLESS=true
      - NAV_TIMEOUT_MS=30000
      - MAX_WAIT_MS=15000
      - USER_AGENT=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
      
      # Configuración del Proxy
      - PROXY_ENABLED=${PROXY_ENABLED:-false}
      - PROXY_ENDPOINT=${PROXY_ENDPOINT:-}
      - PROXY_USERNAME=${PROXY_USERNAME:-}
      - PROXY_PASSWORD=${PROXY_PASSWORD:-}
      
      # Configuración del worker
      - WORKER_CONCURRENCY=${WORKER_CONCURRENCY:-5}

      # Pool de navegadores
      - MAX_CONCURRENT_PAGES=5
      - BROWSER_POOL_SIZE=2
      
      # Logging
      - LOG_LEVEL=info
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G
    networks:
      - resolver-network
    depends_on:
      - redis
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_add:
      - SYS_ADMIN
    shm_size: 2gb

  redis:
    image: redis:7-alpine
    container_name: stream-resolver-redis
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    networks:
      - resolver-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.2'
          memory: 256M
    restart: unless-stopped

  # Opcional: Prometheus para métricas
  prometheus:
    image: prom/prometheus:latest
    container_name: stream-resolver-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    depends_on:
      - api
    networks:
      - resolver-network
    restart: unless-stopped
    profiles:
      - with-monitoring

  # Opcional: Grafana para visualización
  grafana:
    image: grafana/grafana:latest
    container_name: stream-resolver-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./docker/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./docker/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    depends_on:
      - prometheus
    networks:
      - resolver-network
    restart: unless-stopped
    profiles:
      - with-monitoring

networks:
  resolver-network:
    driver: bridge
    name: stream-resolver-network

volumes:
  prometheus-data:
    name: stream-resolver-prometheus-data
  grafana-data:
    name: stream-resolver-grafana-data
  redis-data:
    name: stream-resolver-redis-data
